server:
 port: 8888
 
spring:
 application:
  name: gateway
 cloud:
  gateway:
   routes:
    - id: psr
      predicates:
      - Path=/productapp/**
      uri: lb://product-service
    - id: csr
      predicates:
      - Path=/shoppingcart/**
      uri: lb://cart-service
 
 
  
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:7777/eureka
  
management:
 endpoints:
  web:
   exposure:
    include: "*"
 security:
  enabled: false